
export enum GamePlatformsEnum {
  PS='PS',
  PS2='PS2',
  PS3='PS3',
  PS4='PS4',
  PS5='PS5',
  PSP='PSP',
  XBOX ='XBOX',
  XBOX_360='XBOX 360',
  XBOX_ONE='XBOX ONE',
  XBOX_SERIES_S="XBOX SERIES S",
  XBOX_SERIES_X="XBOX SERIES X",
  SUPER ="SUPER NINTENDO",
  NINTENDO_64="NINTENDO 64",
  NINTENDO_SWITCH="NINTENDO SWITCH",
  NINTENDO_WII="NINTENDO WII",
  NINTENDO_DS="NINTENDO DS",
  NINTENDO_3DS="NINTENDO 3DS",
  MEGA_DRIVE="MEGA DRIVE",
  PC = "PC",
  MOBILE ="MOBILE"

  
}
